// Curated family photos for backgrounds, hero carousel, and the memories strip.
// Source: public/photos/manifest.json (generated by scripts/import-photos.js)

export interface Photo {
  id: string;
  src: string;
  thumb: string;
  width: number;
  height: number;
  aspect: number;
  portrait: boolean;
}

let cached: Photo[] | null = null;
let pending: Promise<Photo[]> | null = null;

export async function loadPhotos(): Promise<Photo[]> {
  if (cached) return cached;
  if (!pending) {
    pending = fetch('/photos/manifest.json')
      .then((r) => (r.ok ? r.json() : []))
      .then((p: Photo[]) => { cached = p; return p; })
      .catch(() => { cached = []; return []; });
  }
  return pending;
}

export function pickRandom<T>(list: T[]): T | undefined {
  if (!list.length) return undefined;
  return list[Math.floor(Math.random() * list.length)];
}

export function shuffle<T>(list: T[]): T[] {
  const a = list.slice();
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}
